name: Node.js Package

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.18.2
          registry-url: https://registry.npmjs.org/

      - run: npm i -g pnpm
      - run: pnpm i
      - run: pnpm build:hooks
      - run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
